= extern keyword

Question: What is `extern`?

== Overview

The `extern` keyword in C is used to declare a variable or function
that is defiened in another file or in another part of the program.
It tells the compiler:
====
"This variable or function exists, but its memory is allocated elsewhere."
====

== Usage

. Sharing variables across multiple files
+
Suppose we define a global valiable in one file:
+
[source,c]
----
// file1.c
int counter = 0; // Global variable
----
+
We can access this variable in another file like this:
+
[source,c]
----
// file2.c
extern int counter;

void increment() {
    counter++;
}
----
+
`extern` prevents a new definition of `counter` in `file2.c`.
It only declares the variable.

. Function declarations

**Functions are `extern` by default,**
but we can explicitly declare them as `extern`:
[source,c]
----
extern void print_message(void);
----
This is useful for clarity, especially in header files.

== Common Mistakes

* Using `extern` without a matching definition in some file will lead to a linker error.
* If we write `extern int counter = 5;`, we're actually defining it (not just declaring). +
The initializer makes it a definition.

